spring.datasource.url=jdbc:postgresql://localhost:5432/employee_management
spring.datasource.username=postgres
spring.datasource.password=12345

jwt.secret=supersecretkey12345678910jwtsecretkey0987654321supersecretkey0
jwt.expiration=3600000

logging.level.com.example.employeemanagement=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
